on:
  push:
    paths:
      - '**/*.lua'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Luacheck Linter
      uses: judaew/luacheck-action@v0.2.1
      with:
        targets: "."
        args: "--include-files **/*.lua"
